"""Container/frame-level golden vector for the V2 file format.

Unlike test_v2_header_parser.py's golden fixtures (hand-derived HKDF/Argon2id/
grant-header vectors, independent of the app's own encoder), this fixture was
generated by the real `encrypt_v2_file` (see tools/generate_v2_vectors.py) and
checked into git as a fixed binary file. Frame nonces/salts are randomly
generated on every encryption by design, so this is necessarily a decrypt-only
golden vector: it does not prove byte-identical re-encryption, but it does
prove the checked-in container — a permanent stand-in for "a real file a user
already has on disk" — keeps decrypting correctly, and it pins the actual wire
byte layout (frame magic/index/lengths/flags), not just round-trip behavior.
A future change to the frame or container format that breaks backward
compatibility with already-encrypted files fails this test immediately.
"""

from __future__ import annotations

import hashlib
import json
import struct
from pathlib import Path

import pytest

from secure_string_cipher.utils import CryptoError
from secure_string_cipher.v2.decrypt import decrypt_v2_file
from secure_string_cipher.v2.encrypt import PasswordCredential
from secure_string_cipher.v2.header_parser import parse_header_stream

FIXTURES_DIR = Path(__file__).parent.parent / "fixtures" / "v2"
MANIFEST_PATH = FIXTURES_DIR / "manifest.json"
CONTAINER_PATH = FIXTURES_DIR / "golden_two_frame_container.ssc"

FRAME_MAGIC = b"S2FR"
# S2FR || frame_index(8) || pt_len(4) || pad_len(2) || flags(1)
FRAME_HEADER_LEN = 4 + 8 + 4 + 2 + 1
TAG_LEN = 16


def _vector() -> dict:
    manifest = json.loads(MANIFEST_PATH.read_text("utf-8"))
    return manifest["container"]["password_two_frame"]


def _expected_plaintext(length: int) -> bytes:
    return bytes((i * 7 + 3) % 256 for i in range(length))


def test_golden_container_fixture_bytes_are_unchanged() -> None:
    """The checked-in fixture itself must not have silently drifted."""
    vector = _vector()
    actual = CONTAINER_PATH.read_bytes()
    assert len(actual) == vector["container_length"]
    assert hashlib.sha256(actual).hexdigest() == vector["container_sha256"]


def test_golden_container_decrypts_to_the_recorded_plaintext(tmp_path: Path) -> None:
    vector = _vector()
    plaintext = _expected_plaintext(vector["plaintext_length"])
    assert hashlib.sha256(plaintext).hexdigest() == vector["plaintext_sha256"]

    output_path = tmp_path / "decrypted.bin"
    result_path = decrypt_v2_file(
        input_path=CONTAINER_PATH,
        credential=PasswordCredential(vector["password"]),
        output_path=output_path,
    )
    assert result_path == output_path
    assert output_path.read_bytes() == plaintext


def test_golden_container_wrong_password_fails_closed() -> None:
    with pytest.raises(CryptoError):
        decrypt_v2_file(
            input_path=CONTAINER_PATH,
            credential=PasswordCredential("definitely-the-wrong-password"),
            output_path=CONTAINER_PATH.parent / "should-not-be-written.bin",
        )
    assert not (CONTAINER_PATH.parent / "should-not-be-written.bin").exists()


def test_golden_container_pins_exact_frame_wire_layout() -> None:
    """Structural check independent of decryption: confirms the checked-in
    container has exactly two frames, in the exact byte layout the frame
    format defines (magic, index, lengths, flags), with the FINAL flag set
    on only the second (last) frame. This is what makes it a frame-level
    vector rather than only a round-trip test."""
    vector = _vector()
    raw = CONTAINER_PATH.read_bytes()

    with open(CONTAINER_PATH, "rb") as f:
        header, _ = parse_header_stream(f)
        frame_section_start = f.tell()

    chunk_size = vector["chunk_size"]
    frames_bytes = raw[frame_section_start:]

    # Frame 0: non-final, full chunk_size plaintext, no padding.
    offset = 0
    magic0 = frames_bytes[offset : offset + 4]
    index0 = struct.unpack("<Q", frames_bytes[offset + 4 : offset + 12])[0]
    pt_len0 = struct.unpack("<I", frames_bytes[offset + 12 : offset + 16])[0]
    pad_len0 = struct.unpack("<H", frames_bytes[offset + 16 : offset + 18])[0]
    flags0 = frames_bytes[offset + 18]
    assert magic0 == FRAME_MAGIC
    assert index0 == 0
    assert pt_len0 == chunk_size
    assert pad_len0 == 0
    assert flags0 == 0x00  # not FINAL

    frame0_total_len = FRAME_HEADER_LEN + pt_len0 + pad_len0 + TAG_LEN
    offset = frame0_total_len

    # Frame 1: final, remaining plaintext.
    magic1 = frames_bytes[offset : offset + 4]
    index1 = struct.unpack("<Q", frames_bytes[offset + 4 : offset + 12])[0]
    pt_len1 = struct.unpack("<I", frames_bytes[offset + 12 : offset + 16])[0]
    flags1 = frames_bytes[offset + 18]
    assert magic1 == FRAME_MAGIC
    assert index1 == 1
    assert pt_len1 == vector["plaintext_length"] - chunk_size
    assert flags1 == 0x01  # FINAL

    frame1_total_len = FRAME_HEADER_LEN + pt_len1 + TAG_LEN
    # Exact EOF after the final frame: no third frame, no trailing bytes.
    assert offset + frame1_total_len == len(frames_bytes)
    assert header.payload.chunk_size == chunk_size
